---
deploy_user: urbanpulse
deploy_user_shell: /bin/bash
ssh_public_key_file: "~/.ssh/id_ed25519.pub"
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - jq
  - net-tools
  - rsync
  - software-properties-common
  - unattended-upgrades
  - ufw
  - fail2ban
