---
common_deploy_user: "{{ deploy_user | default('urbanpulse') }}"
common_deploy_user_shell: "{{ deploy_user_shell | default('/bin/bash') }}"
common_ssh_public_key_file: "{{ ssh_public_key_file | default('~/.ssh/id_ed25519.pub') }}"
common_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - git
  - gnupg
  - htop
  - jq
  - net-tools
  - rsync
  - software-properties-common
  - unattended-upgrades
  - ufw
  - fail2ban
