apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: urbanpulse

resources:
  - namespace.yaml
  - configmap-cities.yaml
  - configmap-schema.yaml
  - pvc-data.yaml
  - postgis.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
  - pipeline-cronjob.yaml
  - monitoring.yaml


commonLabels:
  app.kubernetes.io/part-of: urbanpulse
