apiVersion: v1
kind: Secret
metadata:
  name: urbanpulse-db-secret
  namespace: urbanpulse
  labels:
    app.kubernetes.io/name: urbanpulse
    app.kubernetes.io/component: database
type: Opaque
stringData:
  POSTGRES_DB: "urbanpulse"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres_password_change_me"
  DATABASE_URL: "postgresql://postgres:postgres_password_change_me@db:5432/urbanpulse"
