city:
  name: Ahmedabad
  state: Gujarat
  country: India
spatial:
  bbox:
  - 72.356712
  - 22.814991
  - 72.802746
  - 23.22784
  crs: EPSG:4326
  center_lat: 23.0225
  center_lon: 72.5714
  buffered_distance_km: 8.0
  boundary_geojson: configs/ahmedabad_boundary.geojson
  aoi_size_km: 45.0
temporal:
  analysis_years:
    start_year: 2000
    end_year: 2025
  dry_season:
    start_month: 10
    end_month: 3
    start_day: 10-01
    end_day: 03-31
stac:
  earth_search_url: https://earth-search.aws.element84.com/v1
  microsoft_pc_url: https://planetarycomputer.microsoft.com/api/stac/v1
  collections:
    sentinel_2: sentinel-2-c1-l2a
    landsat_c2_l2: landsat-c2-l2
