---
deploy_project_remote_dir: "{{ project_remote_dir | default('/opt/urbanpulse') }}"
deploy_k8s_overlay_dir: "{{ k8s_overlay_dir | default(deploy_project_remote_dir ~ '/infra/k8s/overlays/local') }}"
deploy_timeout: 120s
